name: Generate release schedule artifacts
on:
  schedule:
    # At 00:00 on day-of-month 1 in every 3rd month. (i.e. every quarter)
    - cron: "0 0 1 */3 *"
  # on demand
  workflow_dispatch:

jobs:
  create-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # We're going to make a tag that we can we release so we'll need the full history for that
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run spec_zero_versions.py
        run: |
          python spec_zero_versions.py
      - name: setup git
        run: |
          # git will complain if we don't do this first
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: determine tag name
        id: tag_name
        run: |
          echo "TAG_NAME=$(date '+%Y-Q%q')" >> "$GITHUB_OUTPUT"

      - name: create tag
        env:
          TAG_NAME: ${{ steps.tag_name.outputs.TAG_NAME }}
        run: |
          git add schedule.md chart.md schedule.json
          git commit -m "Update SPEC 0 schedule artifacts"
          git tag  "$TAG_NAME"
          git push origin "$TAG_NAME"

      - name: Publish github release
        uses: softprops/action-gh-release@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          tag_name: ${{ steps.tag_name.outputs.TAG_NAME }}
          make_latest: true
          files: |
            schedule.md
            chart.md
            schedule.json
