name: Generate release schedule artifacts
on:
  push:
    branches: main
  pull_request:
    branches: main
  # on demand
  workflow_dispatch:

jobs:
  create-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.8.14
        with:
          pixi-version: "v0.49.0"
          environments: dev
      - run: |
          pixi run test
